# Generated by Django 4.1 on 2022-11-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Today_condition',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='data',
            name='Today_sunrise',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='Today_sunset',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='Today_wind',
            field=models.FloatField(default=''),
        ),
    ]
