# Generated by Django 4.1 on 2022-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_data_today_condition_alter_data_today_sunrise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Today_condition',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Today_sunrise',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Today_sunset',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Today_wind',
        ),
    ]
