# Generated by Django 4.1 on 2022-11-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_data_conditionvsdate_alter_data_tempvsdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ConditionVsDate',
        ),
        migrations.RemoveField(
            model_name='data',
            name='TempVsDate',
        ),
    ]
