# Generated by Django 4.1 on 2022-11-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_data_conditionvsdate_remove_data_tempvsdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='TempVsDate',
            field=models.ImageField(default='Sorry Image Is Unabailabe', upload_to='weather/images'),
        ),
    ]
