# Generated by Django 4.1 on 2022-11-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_data_tempvsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='TempVsDate',
            field=models.FileField(default='Sorry Image Is Unabailabe', upload_to='weather/images'),
        ),
    ]
