# Generated by Django 4.1 on 2022-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_remove_data_tempvsdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ConditionVsDate',
            field=models.ImageField(default='Something went wrong', upload_to='weather/images'),
        ),
        migrations.AddField(
            model_name='data',
            name='TempVsDate',
            field=models.ImageField(default='Sorry Image Is Unabailabe', upload_to='weather/images'),
        ),
        migrations.AddField(
            model_name='data',
            name='Today_condition',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='data',
            name='Today_wind',
            field=models.FloatField(default=''),
        ),
    ]
