# Generated by Django 4.1 on 2022-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_data_conditionvsdate_data_tempvsdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Today_Temp',
            field=models.FloatField(default=''),
        ),
    ]
