# Generated by Django 4.1 on 2022-11-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_alter_data_today_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
