# Generated by Django 4.1 on 2022-11-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Today_Temp',
            field=models.FloatField(default='Something Wrong'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Today_condition',
            field=models.CharField(default='Something wrong', max_length=40),
        ),
        migrations.AlterField(
            model_name='data',
            name='Today_wind',
            field=models.FloatField(default='Something wrong'),
        ),
    ]
