# Generated by Django 4.1 on 2022-11-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0019_remove_data_conditionvsdate_remove_data_tempvsdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
