# Generated by Django 4.1 on 2022-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ConditionVsDate',
            field=models.ImageField(default='weather/images/Bag.jfif', upload_to='weather/images'),
        ),
        migrations.AddField(
            model_name='data',
            name='TempVsDate',
            field=models.ImageField(default='weather/images/Bag.jfif', upload_to='weather/images'),
        ),
    ]
