# Generated by Django 4.1 on 2022-11-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0024_remove_data_conditionvsdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='TempVsDate',
        ),
    ]
