# Generated by Django 4.1 on 2022-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0026_data_conditionvsdate_data_tempvsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ConditionVsDate',
            field=models.ImageField(default='weather/images/Error.png', upload_to='weather/images'),
        ),
        migrations.AlterField(
            model_name='data',
            name='TempVsDate',
            field=models.ImageField(default='weather/images/Error.png', upload_to='weather/images'),
        ),
    ]
