# Generated by Django 4.1 on 2022-11-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0030_alter_data_conditionvsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ConditionVsDate',
            field=models.ImageField(blank=True, default='weather/images/Error.png', null=True, upload_to='weather/images'),
        ),
        migrations.AlterField(
            model_name='data',
            name='TempVsDate',
            field=models.ImageField(blank=True, default='/media/weather/images/Error.png', null=True, upload_to='weather/images'),
        ),
    ]
